### ISSUE TITLE
Instructions in readme are incorrect for checking out

### ISSUE THREAD

**Issue by pschlump** [StephenGrider/ReduxSimpleStarter#107]
Following the instructions I get:

> git clone git@github.com:StephenGrider/ReduxSimpleStarter.git
Cloning into 'ReduxSimpleStarter'...
Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
Permission denied (publickey).

You should have:

> git clone https://github.com/StephenGrider/ReduxSimpleStarter.git

Using "git@" implies a login that only you possess.

**Comment by StephenGrider** [comment]
Fixed!
