### ISSUE TITLE
npm start - not working Windows 10

### ISSUE THREAD

**Issue by LadikCZ** [StephenGrider/ReduxSimpleStarter#123]
Hello, 

i got following error when i try to run npm start from project folder.

Can someone please help?
Thank you.

![npm_start](https://cloud.githubusercontent.com/assets/23096126/26344166/f6bc2830-3f9e-11e7-94fe-8a7fd25312ae.png)

**Comment by IrvingArmenta** [comment]
Hello, it seems to me that you haven't installed the packages from the `package.json` file, in that same folder, you need to run `npm install` and wait for all the packages to install, and then run `npm start` 

Did you install them?

**Comment by LadikCZ** [comment]
Yeah but I overelooked some errors during install - this solved my issue https://stackoverflow.com/questions/35809551/npm-err-package-json-must-be-actual-json-not-just-javascript
