### ISSUE TITLE
npm start problem/issue 

### ISSUE THREAD

**Issue by jayshakes** [StephenGrider/ReduxSimpleStarter#130]
> redux-simple-starter@1.0.0 start /Applications/MAMP/htdocs/react/ReduxSimpleStarter
> node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redux-simple-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shikongo/.npm/_logs/2017-06-13T04_45_44_375Z-debug.log

**Comment by dougaraujos** [comment]
+1

**Comment by jayshakes** [comment]
got it working by installing [yarn](https://yarnpkg.com/en/docs/install) 
and adding host:8080 to my webpack.config.js
 `devServer: {
    historyApiFallback: true,
    contentBase: './',
    host:8080
  }`
