### ISSUE TITLE
signin form can not get email and password

### ISSUE THREAD

**Issue by ttson24** [StephenGrider/ReduxSimpleStarter#157]
i am follow this lesson. i now studying client package, when i create signin form  but signin button press, in handleFormSubmit function email and password alway undefine.
Could you help me!!

**Comment by Christophosaurus** [comment]
+1
I have gone over the code time and time again, and cannot see any difference between files. 

import React, {Component} from 'react';
import {reduxForm} from 'redux-form';

class SignIn extends Component {

    handleFormSubmit({email, password}) {
        console.log(email, password);
    }

    render() {

        const { handleSubmit, fields: {email, password}} = this.props;

        return (
            <form onSubmit={handleSubmit(this.handleFormSubmit.bind(this))}>
                <fieldset className="form-group">
                    <label>Email:</label>
                    <input {...email} className="form-control" />
                </fieldset>
                <fieldset className="form-group">
                    <label>Password:</label>
                    <input {...password} type="password" className="form-control" />
                </fieldset>
                <button action="submit" className="btn btn-primary">Sign in</button>
            </form>
        );
    }
}

export default reduxForm({
    form: 'signin',
    fields: ['email', 'password']
})(SignIn);

**Comment by Christophosaurus** [comment]
@ttson24 I believe this is due to changes in redux-form

if you downgrade redux-form to use version ^5.3.3 (delete node modules and npm install again) then you should get the values as expected. 

i ran into the same issues then remembered there is an updated version of react router in the previous course Stephen uploaded `Moden React with Redux

hope this helps

**Comment by afropaul** [comment]
+1 for the downgrade to redux-form@5.3.3, works.

**Comment by ttson24** [comment]
thank a lot, i ran.!!!
