### ISSUE TITLE
Super expression must either be null or a function...

### ISSUE THREAD

**Issue by josecaballero** [StephenGrider/ReduxSimpleStarter#164]
Hey guys,

If I import my component as it follows with ES6:

import React, { Component } from 'react';
class SearchBar extends React {
  render() {
    return <input onChange = {this.onInputChange} />;
  }

it throws this error: Uncaught TypeError: Super expression must either be null or a function, not object

But with the old sintax it works:

import React from 'react';
class SearchBar extends React.Component {
  render() {
    return <input onChange = {this.onInputChange} />;
  }

Any idea to make it work with ES6?

Thanks!

**Comment by dsxragnarok** [comment]
You need to extend from **Component** not **React**.

`class SearchBar extends Component`

**Comment by monsieurkayode** [comment]
Spot on @dsxragnarok

**Comment by josecaballero** [comment]
Thanks 👍
