### ISSUE TITLE
npm start is not working

### ISSUE THREAD

**Issue by sandyksit** [StephenGrider/ReduxSimpleStarter#17]
Hi @StephenGrider   when I ran with npm start command for ReduxSimpleStarter, its showing npm-debug.log. below are the npm-debug.log. 
----------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.4
3 info using node@v4.1.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart redux-simple-starter@1.0.0
6 info start redux-simple-starter@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info redux-simple-starter@1.0.0 Failed to exec start script
9 verbose stack Error: redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid redux-simple-starter@1.0.0
11 verbose cwd D:\docs\sample\ReduxSimpleStarter
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.1.2
15 error npm  v2.14.4
16 error code ELIFECYCLE
17 error redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
17 error Exit status 1
18 error Failed at the redux-simple-starter@1.0.0 start script 'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
18 error This is most likely a problem with the redux-simple-starter package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
18 error You can get their info via:
18 error     npm owner ls redux-simple-starter
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by magalhini** [comment]
I had the same issue, and it turns out my cloned copy completely ignored the `.babelrc` file. Make sure this file is present in your local copy and that it contains the babel configuration.

**Comment by sandyksit** [comment]
Thanks @magalhini for reply,When I install new node version then npm is working fine.
