### ISSUE TITLE
Fixed Cannot resolve module 'react-router-dom'

### ISSUE THREAD

**Issue by 4mifix** [StephenGrider/ReduxSimpleStarter#181]
Lecture 121 time on video around 5:45

The _router_ has to be _installed with_ **npm i react-router-dom --save**

ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'react-router-dom' in /Users/brianmayers/blog/src
 @ ./src/index.js 17:22-49

**Comment by joshuapinter** [comment]
Thanks for this! 

All the instructions said to install `react-router` but then my imports would fail for `react-router-dom`. Changing the `package.json` dependency to `react-router-dom` worked great.

**Comment by ShravanMeena** [comment]
did you install react, react-dom, react-router-dom?

If not are not installed then :>>
 npm i react react-dom react-router-dom

**Comment by DCorp617** [comment]
> did you install react, react-dom, react-router-dom?
> 
> If not are not installed then :>>
> npm i react react-dom react-router-dom

Thanks @ShravanMeena, this solved the issue for my "cannot find module 'rea ct-router-dom'" problem.

**Comment by Tekdokto** [comment]
Woooow Thanks @ShravanMeena,...God bless you, it solved the problem of cannot find module 'react-router-dom' instantly

**Comment by plmnavrmv** [comment]
Problem solved fast and easy , thanks !

**Comment by AlexMo-Rogers** [comment]
Implicitly referencing the type worked for me: `**npm install --save @types/react-router-dom**`

**Comment by taichi-tech** [comment]
I didn't solve it🫠
