### ISSUE TITLE
When searching for a city getting return as Altstadt

### ISSUE THREAD

**Issue by lavebug** [StephenGrider/ReduxSimpleStarter#183]
Section 5 Lecture 62, about 4:50 min into it when I do a search for any city I get Altstadt. I have registered the with openweathermap.org and I have my api key.

**Comment by Antoskin** [comment]
How did you solve the problem ?? I've the same

**Comment by lavebug** [comment]
Make sure index.js in actions/ has this 
const ROOT_URL = `http://api.openweathermap.org/data/2.5/forecast?appid=${API_KEY}`;

**Comment by Antoskin** [comment]
Yes, It was solved, thanks =)

**Comment by daniloanobre** [comment]
The url needs to be "http" not "https". I had to spend some minutes trying to figure out every time openweatherapi was returning the same result.

Thanks, Antoskin

**Comment by emaitee** [comment]
@daniloanobre, take note of the 'api' in the address, http://api.openweathermap.org/data/2.5/forecast?appid=${API_KEY}. I was using 'samples' instead. Thanks for this.
