### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by rcclemente** [StephenGrider/ReduxSimpleStarter#189]
Reviewed the code a couple of times and compared with the video and i can't figure out the code difference

https://github.com/rcclemente/ReduxSimpleStarter/blob/master/src/containers/book-list.js
https://github.com/rcclemente/ReduxSimpleStarter/blob/master/src/reducers/index.js

``` bash 
ERROR in ./src/reducers/index.js
Module build failed: SyntaxError: Unexpected token, expected , (5:21)

  3 |
  4 | const rootReducer = combineReducers({
> 5 |   books: BooksReducer;
    |                      ^
  6 | });
  7 |
  8 | export default rootReducer;

 @ ./src/index.js 19:16-37

ERROR in ./src/containers/book-list.js
Module build failed: SyntaxError: Unexpected token, expected { (4:15)

  2 | import { connect } from 'react-redux';
  3 |
> 4 | class BookList extend Component {
```

**Comment by thpAGGIE910** [comment]
I believe your issue is a typo on line 4 of book-list.js. The line should be
```class BookList extends Component {```

You have a typo on `extend`; it should be `extends`
