### ISSUE TITLE
npm start fails EADDRINUSE (solution)

### ISSUE THREAD

**Issue by rgbm21** [StephenGrider/ReduxSimpleStarter#23]
In case someone gets this:

```
    Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at net.js:1381:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
```
You can have a look at this [EADDRINUSE](http://stackoverflow.com/questions/9204706/node-js-listen-eaddrinuse-error-for-simple-httpserver) and resolve the issue.

OR 

The easy way (**Update your webpack.config.js**) to use a different port:

```
  devServer: {
    historyApiFallback: true,
    contentBase: './',
    inline: true,
    port : 3000
  }
```

**Comment by StephenGrider** [comment]
Good solution, you can also find and end the running process on port 8080.

`lsof -i tcp:8080`

**Comment by zmorris** [comment]
You can also use `-ti` to get the PID of the process directly:

`lsof -ti tcp:8080`

**Comment by kumaresan-subramani** [comment]
bundled files were not displayed

**Comment by ineszribidev** [comment]
> In case someone gets this:
> 
> ```
>     Error: listen EADDRINUSE 127.0.0.1:8080
>     at Object.exports._errnoException (util.js:856:11)
>     at exports._exceptionWithHostPort (util.js:879:20)
>     at Server._listen2 (net.js:1236:14)
>     at listen (net.js:1272:10)
>     at net.js:1381:9
>     at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
> ```
> 
> You can have a look at this [EADDRINUSE](http://stackoverflow.com/questions/9204706/node-js-listen-eaddrinuse-error-for-simple-httpserver) and resolve the issue.
> 
> OR
> 
> The easy way (**Update your webpack.config.js**) to use a different port:
> 
> ```
>   devServer: {
>     historyApiFallback: true,
>     contentBase: './',
>     inline: true,
>     port : 3000
>   }
> ```

Good solution thank you ragmha
