### ISSUE TITLE
Section 5 Lecture 64: Issue with Sparklines 1.6.0

### ISSUE THREAD

**Issue by jamesalmeida** [StephenGrider/ReduxSimpleStarter#259]
I keep getting this error:
`Uncaught TypeError: Cannot read property 'string' of undefined`

I had Sparklines 1.6.0 installed. Tried uninstalling and going back to 1.4.2 and still have same issue. 

The error goes away as soon as I remove this line from my code:
`import { Sparklines, SparklinesLine } from 'react-sparklines';`

Here's a couple screenshots:
<img width="661" alt="screen shot 2018-07-26 at 5 44 39 pm" src="https://user-images.githubusercontent.com/703253/43295820-491463b8-90fc-11e8-9494-95587c3c8501.png">
<img width="909" alt="screen shot 2018-07-26 at 5 51 15 pm" src="https://user-images.githubusercontent.com/703253/43295851-8da25f26-90fc-11e8-9674-7b2510a4ccb3.png">

Anyone know what's going on here?

**Comment by rapahaeru** [comment]
I got the same here.
And this is not the version error what this section alerts.

**Comment by jamesalmeida** [comment]
I ended up just typing `npm install react-sparklines --save` in the terminal and now the error went away. I guess the most recent version works fine now contrary to the note in the course telling us to install the previous 1.6.0 version?
