### ISSUE TITLE
Cannot run tests 

### ISSUE THREAD

**Issue by Uthpala** [StephenGrider/ReduxSimpleStarter#35]
When i clone the reduxsimplestarter and do npm install and npm start 
and try to run npm run test:watch it gives and error. I have pasted the start of it. 

SyntaxError: /home/uthpala/Desktop/ReduxSimpleStarter/test/test_helper.js: Unexpected token (21:4)
  19 | function renderComponent(ComponentClass, props = {}, state = {}) {
  20 |   const componentInstance =  TestUtils.renderIntoDocument(
> 21 |     <Provider store={createStore(reducers, state)}>
     |     ^
  22 |       <ComponentClass {...props} />
  23 |     </Provider>
  24 |   );
    at Parser.pp.raise (/home/uthpala/Desktop/ReduxSimpleStarter/node_modules/babylon/lib/parser/location.js:22:13)

why is happening.

**Comment by kenken17** [comment]
I have the same errors. Any idea?

**Comment by StephenGrider** [comment]
Yep, missing `.babelrc` file
