### ISSUE TITLE
chapter 28 can't get all list items

### ISSUE THREAD

**Issue by joethuoo** [StephenGrider/ReduxSimpleStarter#41]
I got this error from the console chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILED 
But am only getting the first selected video

**Comment by StephenGrider** [comment]
This is apart of how the youtube iframe works, all youtube embeds generate this error.  The player is trying to access some specific chrome extension to see if its available/installed.
