### ISSUE TITLE
Unable to access nested url in production build

### ISSUE THREAD

**Issue by gordonwoon** [StephenGrider/ReduxSimpleStarter#49]
When accessing "localhost/login" directly in webpack-dev-server, it works. But when i access a production build, "localhost/login" doesn't work. The only way would be to access "localhost" then click on a link that brings the page to "localhost/login".

Do i have to setup some configurations in webpack.conf to solve this issue?

**Comment by StephenGrider** [comment]
You're running into the issue exactly described here: https://www.youtube.com/watch?v=cdUyEou0LHg

**Comment by gordonwoon** [comment]
thanks so much Stephen! you're awesome!
