### ISSUE TITLE
es6-enum and action types

### ISSUE THREAD

**Issue by appjitsu** [StephenGrider/ReduxSimpleStarter#51]
@StephenGrider,

This is not necessarily an issue with the repo. I am thoroughly enjoying the Udemy course. It was money well spent!

Anyways, I am at the point in the weather app where you are talking about setting action types as a constant so you can refer to those types later on in the code to make it easier to manage and produce less bugs: see "Ajax Requests with Axios".

So I thought it would be awesome if es6 had a way to make use of enumerations and sure enough I came across an npm package called es6-enum: https://www.npmjs.com/package/es6-enum

I just wanted your feedback on using this package. In the ReadMe, the author says that he typically uses this package for redux actions types.

Thanks!

**Comment by StephenGrider** [comment]
Cool package, it really does suit this use case perfectly
