### ISSUE TITLE
Error on NPM Install

### ISSUE THREAD

**Issue by mrbrackins** [StephenGrider/ReduxSimpleStarter#6]
Getting following error during npm install:

C:\Users\Tony\Desktop\ReduxSimpleStarter>npm install
npm WARN unmet dependency C:\Users\Tony\Desktop\ReduxSimpleStarter\node_modules\babel-core\node_modules\babel-register\node_modules\source-map-support requires source-map@'0.1.32' but will load
npm WARN unmet dependency C:\Users\Tony\Desktop\ReduxSimpleStarter\node_modules\babel-core\node_modules\source-map,
npm WARN unmet dependency which is version 0.5.3

C:\Users\Tony\Desktop\ReduxSimpleStarter>npm update

C:\Users\Tony\Desktop\ReduxSimpleStarter>npm install
npm WARN unmet dependency C:\Users\Tony\Desktop\ReduxSimpleStarter\node_modules\babel-core\node_modules\babel-register\node_modules\source-map-support requires source-map@'0.1.32' but will load
npm WARN unmet dependency C:\Users\Tony\Desktop\ReduxSimpleStarter\node_modules\babel-core\node_modules\source-map,
npm WARN unmet dependency which is version 0.5.3

C:\Users\Tony\Desktop\ReduxSimpleStarter>cd ..

C:\Users\Tony\Desktop>mkdir test

C:\Users\Tony\Desktop>git
'git' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Tony\Desktop>cd test

C:\Users\Tony\Desktop\test>dir
 Volume in drive C is Windows
 Volume Serial Number is 9C4C-9A45

 Directory of C:\Users\Tony\Desktop\test

02/13/16  12:02 PM    <DIR>          .
02/13/16  12:02 PM    <DIR>          ..
02/13/16  12:02 PM    <DIR>          ReduxSimpleStarter-master
               0 File(s)              0 bytes
               3 Dir(s)   3,201,048,576 bytes free

C:\Users\Tony\Desktop\test>cd ReduxSimpleStarter-master

C:\Users\Tony\Desktop\test\ReduxSimpleStarter-master>npm install
npm WARN optional dep failed, continuing fsevents@1.0.7
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! path C:\Users\Tony\AppData\Roaming\npm-cache\babel-types\6.5.2\package\package.json.bb03671f7173999d34fc04fb1f543c97
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Tony\AppData\Roaming\npm-cache\babel-types\6.5.2\package\package.json.bb03671f7173999d34fc04fb1f543c97' -> 'C:\Users\Tony\AppData\Roaming\npm-cache\babel-types\6.5.2\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\Tony\AppData\Roaming\npm-cache\babel-types\6.5.2\package\package.json.bb03671f7173999d34fc04fb1f543c97' -> 'C:\Users\Tony\AppData\Roaming\npm-cache\babel-types\6.5.2\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\Tony\\AppData\\Roaming\\npm-cache\\babel-types\\6.5.2\\package\\package.json.bb03671f7173999d34fc04fb1f543c97',
npm ERR!   dest: 'C:\\Users\\Tony\\AppData\\Roaming\\npm-cache\\babel-types\\6.5.2\\package\\package.json',
npm ERR!   parent: 'babel-template' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Tony\Desktop\test\ReduxSimpleStarter-master\npm-debug.log

C:\Users\Tony\Desktop\test\ReduxSimpleStarter-master>

**Comment by goodbomb** [comment]
```npm ERR! Please try running this command again as root/Administrator.```

This line means you should try running the command as administrator. To do that, use the "sudo" command:

```sudo npm install```

Normally you shouldn't have to do that, but you may have installed Node / npm using the sudo command originally.

Something else you may want to check is your version of node.js. On the command line, type ```node -v``` and if the version returned is below version 4.0.0, then you'll want to update your version of node.js

**Comment by mrbrackins** [comment]
Thanks @goodbomb !
