### ISSUE TITLE
npm start issue on linux 

### ISSUE THREAD

**Issue by karesh** [StephenGrider/ReduxSimpleStarter#83]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle redux-simple-starter@1.0.0~prestart: redux-simple-starter@1.0.0
6 silly lifecycle redux-simple-starter@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle redux-simple-starter@1.0.0~start: redux-simple-starter@1.0.0
8 verbose lifecycle redux-simple-starter@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle redux-simple-starter@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/karesh/web/ReduxSimpleStarter/node_modules/.bin:/home/karesh/deeptool/torch/install/bin:/usr/local/cuda/bin:/home/karesh/deeptool/torch/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda/bin:/usr/local/MATLAB/R2014a/bin:/home/karesh/Android/Sdk/tools:/home/karesh/Android/Sdk/platform-tools
10 verbose lifecycle redux-simple-starter@1.0.0~start: CWD: /home/karesh/web/ReduxSimpleStarter
11 silly lifecycle redux-simple-starter@1.0.0~start: Args: [ '-c',
11 silly lifecycle   'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js' ]
12 silly lifecycle redux-simple-starter@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle redux-simple-starter@1.0.0~start: Failed to exec start script
14 verbose stack Error: redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid redux-simple-starter@1.0.0
16 verbose cwd /home/karesh/web/ReduxSimpleStarter
17 error Linux 3.19.0-68-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error redux-simple-starter@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
22 error Exit status 1
23 error Failed at the redux-simple-starter@1.0.0 start script 'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the redux-simple-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs redux-simple-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls redux-simple-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tomahawkzx** [comment]
The same occurs here. Curiously it worked fine in the last morning, when doing it for the section 1.
I'm using Windows 10 build 14971

@StephenGrider pls halp

**Comment by tomahawkzx** [comment]
After looking some topics regarding this error, I've noticed that its sometimes related with node process stuck. blablabla, so... I restarted and now everything looks fine.

related: [http://theoatmeal.com/blog/fix_computer](http://theoatmeal.com/blog/fix_computer)

**Comment by hinchley2018** [comment]
@karesh This link helped me on Ubuntu https://askubuntu.com/questions/702157/install-node-js-in-ubuntu-14-04

**Comment by karesh** [comment]
Thanks. That is working..
